### ISSUE TITLE
1

### ISSUE THREAD

**Issue by DPMD** [hellohaidev/devsiska#1]
Pembangunan Posyandu kode **2209**
pemeliharaan jalan desa **2301**
pembangunan  batas tanah desa **1507**

@hellohaidev

**Comment by DPMD** [comment]
![Design Interface Super Siskeudes](https://user-images.githubusercontent.com/50356086/57279803-24d72280-70d3-11e9-9980-dee96e546f44.jpg)

**Comment by hellohaidev** [comment]
- langkah awal akan di ujicoba penarikan data posyandu

- lalu jalan desa dan batas tanah desa

**Comment by DPMD** [comment]
baik . dicoba pak
