### ISSUE TITLE
fix bug tampilan error realisasi

### ISSUE THREAD

**Issue by hellohaidev** [hellohaidev/devsiska#11]
setelah memilih kegiatan dan pada tombol realisasi terdapat error ketika data tidak ada
![Screen Shot 2019-06-12 at 09 16 37](https://user-images.githubusercontent.com/45312271/59319097-a41fcd80-8cf3-11e9-9f22-4a3261ac9182.png)

**Solusi**
Berikan logika apabila total anggaran,total volume,satuan kosong dengan membuat notifikasi 
misal : data belum ada

**Comment by syarifonta** [comment]
akan muncul seperti gambar diatas ketika database kosong?

**Comment by hellohaidev** [comment]
ya ketika data tidak ada pada,maka diperlukan handle error pada tampilan
![Screen Shot 2019-06-12 at 10 02 32](https://user-images.githubusercontent.com/45312271/59320675-632ab780-8cf9-11e9-9737-d40cdd910f23.png)

misal seperti gambar di atas
