### ISSUE TITLE
redesign kolom anggaran

### ISSUE THREAD

**Issue by hellohaidev** [hellohaidev/devsiska#12]
ubah design block anggaran yg terdapat pada tampilan dashboard sehingga menjadi responsive
link resoure 
https://adminlte.io/themes/AdminLTE/index2.html

**Comment by syarifonta** [comment]
seluruh block pada dashboard? dibuat sesuai dengan admin lte v 2?

**Comment by hellohaidev** [comment]
ya seluruh block saja agar dapat responsive
