### ISSUE TITLE
tampilkan total anggaran kegiatan

### ISSUE THREAD

**Issue by hellohaidev** [hellohaidev/devsiska#8]
Tampilkan total anggaran desa se Kabupaten Bogor pada dashboard,tampilan seperti di bawah ini 

![Screen Shot 2019-05-27 at 09 41 21](https://user-images.githubusercontent.com/45312271/58392429-19d53980-8064-11e9-83e9-1e1c8ccd61ff.png)

**Comment by syarifonta** [comment]
total anggaran berupa jumlah dari seluruh kegiatan dalam bentuk rupiah?

**Comment by hellohaidev** [comment]
tampilkan dalam format rupiah
